# Generated by Django 2.2.5 on 2019-10-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_productfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='checksum',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
