# Generated by Django 2.2.5 on 2019-11-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20191007_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='is_digital',
            field=models.BooleanField(default=False),
        ),
    ]
