# Generated by Django 2.2.5 on 2019-11-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_productclass_is_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclass',
            name='is_digital',
            field=models.BooleanField(default=False, verbose_name='Is digital?'),
        ),
    ]
