# Generated by Django 2.2.8 on 2019-12-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_productfile_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='filename',
            field=models.CharField(max_length=255),
        ),
    ]
