# Generated by Django 2.2.8 on 2019-12-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_auto_20191219_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadAttempt',
        ),
    ]
