# Generated by Django 2.2.8 on 2019-12-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_delete_downloadattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productclass',
            name='is_digital',
        ),
        migrations.AddField(
            model_name='productclass',
            name='is_downloadable',
            field=models.BooleanField(default=False, verbose_name='Is downloadable?'),
        ),
    ]
